/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    WeatherAnimate: typeof import('./src/components/WeatherAnimate.vue')['default']
    WeatherInfo: typeof import('./src/components/WeatherInfo.vue')['default']
    WeatherMain: typeof import('./src/components/WeatherMain.vue')['default']
    WeatherSearch: typeof import('./src/components/WeatherSearch.vue')['default']
  }
}
